# Meta
ink: "3.1.10"
jekyll: "3.3.1"

# Site settings
title: Art Bergmann
email: webmaster@artbergmann.com
description: >
  Official website of Art Bergmann, anti-hero-iconoclast of Canadian music for over 40 years.
url: "http://va7sdf.github.io"
baseurl: ""

# Debugging
debug: false

# Build settings
markdown: kramdown

# Global post settings
excerpt_separator: <!--more-->

# Exclude list
exclude:
  - "*/lyrics"
  - "*/README.md"   # README files anywhere in tree
  - "scripts"
  - "import"
  - "README.md"     # root README file

defaults:
  -
    scope:
      path: "albums"
      type: "posts"
    values:
      layout: "lyrics"
      permalink: /:categories/:title.html
  -
    scope:
      path: "albums"
      type: "pages"
    values:
      layout: "album"
  -
    scope:
      path: "press"
      type: "posts"
    values:
      layout: "article"
      permalink: /:categories/:title.html
  -
    scope:
      path: "press"
      type: "pages"
    values:
      layout: "period"

collections:
  - videos
