# Site settings
title: Art Bergmann Fan Site
email: webmaster@artbergmann.rocks
description: > # this means to ignore newlines until "baseurl:"
  A fan site dedicated to the music of Art Bergmann.
baseurl: "/artbergmann" # the subpath of your site, e.g. /blog/
url: "http://va7sdf.github.io" # the base hostname & protocol for your site
twitter_username: va7sdf
github_username:  va7sdf

# Build settings
markdown: kramdown

# Exclude list
exclude:
  - "*/images"
  - "*/thumbs"
  - "*/lyrics"
  - "*/README.md"   # README files anywhere in tree
  - "scripts"
  - "README.md"     # root README file

defaults:
  -
    scope:
      path: "albums"
      type: "posts"
    values:
      layout: "lyrics"
      author: "Dr. Applefritter"
      permalink: /:categories/:title.html
  -
    scope:
      path: "albums"
      type: "pages"
    values:
      layout: "albums"
      author: "Dr. Applefritter"
